import React, { forwardRef, useState, useEffect, useCallback } from 'react';
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import { Alert, Grid, Button, TextField, Tooltip, CircularProgress } from '@mui/material'


const Claim = () => {

    const [loading, setLoading] = useState(false);
    const [exists, setExists] = useState(false);
    const [checked, setChecked] = useState(false);

    const handleCheck = () => {
        setLoading(true);
        setTimeout(() => {
            setLoading(false);
            setExists(false);
            setChecked(true);
        }, [1000]);
    }

    const handleClaim = () => {
        alert("Claimed");
    }


    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Claim Your Account</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Nav />

                <Grid container className="row-container">
                    <Grid item md={12}>
                        <div className="bar info"></div>
                        <h1>Claim</h1>
                    </Grid>
                    <Grid item md={4}></Grid>
                    <Grid item md={4}>
                        <Grid container spacing={2}>
                            <Grid item md={12}>
                                {
                                    (exists) ?
                                        <Alert severity='success'>Account Exists</Alert>
                                    :
                                        (checked) ? 
                                        <Alert severity='error'>Account does not exist, but you can create one <Link href="/register">here</Link>!</Alert>
                                        :
                                        null
                                }
                            </Grid>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" label="Email" />
                            </Grid>
                            <Grid item md={12} sx={{ textAlign: 'center' }}>
                                {
                                    (!loading) ?
                                        (!exists) ?
                                            <button className="button-info" style={{ width: '60%' }} onClick={handleCheck}>Check if Account Exists</button>
                                        :
                                            <button className="button-info" style={{ width: '60%' }} onClick={handleClaim}>Claim Account</button>

                                    :
                                        <CircularProgress />
                                }
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid item md={4}></Grid>
                </Grid>
            </div>
        </>
    );
}

export default Claim;