import React, { forwardRef, useState, useEffect, useCallback } from 'react';
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import { Grid, Button, TextField, Tooltip } from '@mui/material'
import QuestionMarkIcon from '@mui/icons-material/QuestionMark';

const Claim = () => (
    <Tooltip title="If you've signed up for a class in the past, an account has already been made for you. Claim it here."><span style={{ width: '1rem', height: '1rem', marginLeft: '5px', color: '#3B89C7' }}>(?)</span></Tooltip>
)


const Login = () => {

    const [loading, setLoading] = useState(false);

    useEffect(() => {

    }, [])

    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Classes and Events</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Nav />

                <Grid container className="row-container">
                    <Grid item md={12}>
                        <div className="bar info"></div>
                        <h1>Login</h1>
                    </Grid>
                    <Grid item md={3}></Grid>
                    <Grid item md={6}>
                        <Grid container spacing={2}>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" label="Email" />
                            </Grid>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="password" label="Password" />
                            </Grid>
                            <Grid item md={12} sx={{ textAlign: 'center' }}>
                                <button className="button-info" style={{ width: '60%' }}>Login</button>
                            </Grid>
                            <Grid item md={12} sx={{ textAlign: 'center' }}>
                                <span><Link href="/register">Need an Account?</Link></span> | <span><Link href="/">Forgot your password?</Link></span> | <span><Link href="/claim">Claim your account</Link><Claim /></span>
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid item md={4}></Grid>
                </Grid>
            </div>
        </>
    );
}

export default Login;