import React, { forwardRef, useState, useEffect, useCallback } from 'react';
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import { CircularProgress, Grid, TextField } from '@mui/material'


const Register = () => {

    const [loading, setLoading] = useState(false);
    const [clicked, setClicked] = useState(false);
    const [errors, setErrors] = useState(null);


    const handleRegister = () => {
        setLoading(true);
        setTimeout(() => {
            setErrors(null);
            setClicked(true);    
        }, [1000]);
    }


    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Register</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Nav />

                <Grid container className="row-container">
                    <Grid item md={12}>
                        <div className="bar info"></div>
                        <h1>Register</h1>
                    </Grid>
                    <Grid item md={4}></Grid>
                    <Grid item md={4}>
                        <Grid container spacing={2}>
                            <Grid item md={12}>
                                <Grid container spacing={2}>
                                    <Grid item md={6}>
                                        <TextField sx={{ width: '99%' }} variant="standard" label="First Name" />
                                    </Grid>
                                    <Grid item md={6}>
                                        <TextField sx={{ width: '99%' }} variant="standard" label="Last Name" />
                                    </Grid>
                                </Grid>
                            </Grid>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" label="Email" />
                            </Grid>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="password" label="Password" />
                            </Grid>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="password" label="Repeat Password" />
                            </Grid>
                            <Grid item md={12} sx={{ textAlign: 'center' }}>
                                {
                                    (!loading) ?
                                        <button className="button-info" style={{ width: '60%' }} onClick={handleRegister}>Register</button>
                                    :
                                        (!clicked) ?
                                        <CircularProgress />
                                        :
                                        <span>Yes</span>
                                }
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid item md={4}></Grid>
                </Grid>
            </div>
        </>
    );
}


export default Register;