import React, { forwardRef, useState, useEffect, useCallback } from 'react';
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Nav from '../components/Nav'
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";

import { CircularProgress, FormControl, Grid, InputLabel, MenuItem, Select, TextField } from '@mui/material'


const Submit = () => {

    const [loading, setLoading] = useState(false);
    const [clicked, setClicked] = useState(false);
    const [errors, setErrors] = useState(null);


    const handleRegister = () => {
        setLoading(true);
        setTimeout(() => {
            setErrors(null);
            setClicked(true);    
        }, [1000]);
    }

    const CustomText = forwardRef(({ value, onClick }, ref) => (
        <FormControl fullWidth>
          <TextField onClick={onClick} ref={ref} value={value} variant="outlined" />
        </FormControl>
      ));
    CustomText.displayName = "CustomText";


    return(
        <>
            <div className={styles.container}>
                <Head>
                    <title>Submit A New Class</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Nav />

                <Grid container className="row-container">
                    <Grid item md={12}>
                        <div className="bar info"></div>
                        <h1>Submit A New Class/Event/Support Group</h1>
                    </Grid>
                    <Grid item md={4}></Grid>
                    <Grid item md={4}>
                        <Grid container spacing={2}>
                            <Grid item md={12}>
                                <Grid container spacing={2}>
                                    <Grid item md={12}>
                                        <FormControl fullWidth>
                                            <InputLabel>Class Type</InputLabel>
                                            <Select label="Department">
                                                <MenuItem>Class</MenuItem>
                                                <MenuItem>Event</MenuItem>
                                                <MenuItem>Support Group</MenuItem>
                                            </Select>
                                        </FormControl>
                                    </Grid>
                                    <Grid item md={6}>
                                        <FormControl fullWidth>
                                            <InputLabel>Department</InputLabel>
                                            <Select label="Department">
                                                <MenuItem></MenuItem>
                                            </Select>
                                        </FormControl>
                                    </Grid>
                                    <Grid item md={6}>
                                        <TextField sx={{ width: '99%' }} variant="standard" label="Name" />
                                    </Grid>
                                </Grid>
                            </Grid>
                            <Grid item md={12}>
                                <TextField sx={{ width: '99%' }} variant="standard" label="Description" rows={4} />
                            </Grid>
                            <Grid item md={6}>
                                <FormControl fullWidth>
                                    <InputLabel>Start Date</InputLabel>
                                    <DatePicker
                                        customInput={<CustomText />}
                                        selectsRange
                                    />
                                </FormControl>
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Start Time" />
                            </Grid>
                            <Grid item md={6}>
                                <FormControl fullWidth>
                                    <InputLabel>End Date</InputLabel>
                                    <DatePicker
                                        customInput={<CustomText />}
                                        selectsRange
                                    />
                                </FormControl>
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="End Time" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Participation Limit" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Cost" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Contact Name" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Contact Phone" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Contact Email" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Time Slots" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Time Slot Interval" />
                            </Grid>
                            <Grid item md={6}>
                                <TextField sx={{ width: '99%' }} variant="standard" type="text" label="Registrants Per Time Slot" />
                            </Grid>
                            <Grid item md={12}>
                                
                            </Grid>
                            <Grid item md={12} sx={{ textAlign: 'center' }}>
                                {
                                    (!loading) ?
                                        <button className="button-info" style={{ width: '60%' }} onClick={handleRegister}>Submit</button>
                                    :
                                        (!clicked) ?
                                        <CircularProgress />
                                        :
                                        <span>Yes</span>
                                }
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid item md={4}></Grid>
                </Grid>
            </div>
        </>
    );

}

export default Submit;